call pathogen#infect()

call pathogen#helptags()

syntax enable
set background=dark
let g:solarized_termtrans=1
colorscheme solarized

set guifont=Menlo:h13
set number

set softtabstop=4 shiftwidth=4 expandtab

" use ctrl-v to determine the key code for fn-f2
"set pastetoggle=<F2>
set pastetoggle=OQ
